### ISSUE TITLE
Fails to find module 'ctags'

### ISSUE THREAD

**Issue by mhartington** [c0r73x/neotags.nvim#1]
Looks like trying to call `UpdateRemotePlugins` throws an error.

```
Encountered ImportError loading plugin at /Users/mhartington/.config/nvim/.dein/rplugin/python3/neotags: No module named 'ctags'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 132, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
ImportError: No module named 'ctags'
```

Seems there is no ctags module to import. Any ideas?

**Comment by c0r73x** [comment]
Can you try now, I removed that dependacy a minute ago :)

**Comment by mhartington** [comment]
heh, will try 😄

**Comment by mhartington** [comment]
Looks good!

**Comment by c0r73x** [comment]
I noticed a problem though, because i switched to use taglist() instead of parsing the ctags file neotags deadlocks the same way as easytags when opening large projects. I will try to fix it.
