### ISSUE TITLE
No module name 'neovim.api.nvim'

### ISSUE THREAD

**Issue by MikaYuoadas** [c0r73x/neotags.nvim#36]
When starting neovim I get this traceback:
```python
no notification handler registered for "/home/asadaoui/.config/nvim/plugged/neotags.nvim/rplugin/python3/neotags:function:NeotagsInit"                         
Encountered ModuleNotFoundError loading plugin at /home/asadaoui/.config/nvim/plugged/neotags.nvim/rplugin/python3/neotags: No module named 'neovim.api.nvim'  
Traceback (most recent call last):                                                                                                                             
  File "/usr/lib/python3.7/site-packages/pynvim/plugin/host.py", line 135, in _load                                                                            
    module = imp.load_module(name, file, pathname, descr)                                                                                                      
  File "/usr/lib/python3.7/imp.py", line 244, in load_module                                                                                                   
    return load_package(name, filename)                                                                                                                        
  File "/usr/lib/python3.7/imp.py", line 216, in load_package                                                                                                  
    return _load(spec)                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 696, in _load                                                                                                     
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                                                            
ModuleNotFoundError: No module named 'neovim.api.nvim'
```

I'm using Neovim v0.3.1

It looks like the python module was renamed from neovim to pynvim. (see [this commit](https://github.com/neovim/pynvim/commit/f2372385d1be6ed62ee458d5e017fff3541ce0f7))

**Comment by MikaYuoadas** [comment]
I've created a small pull request that fix the issue on my setup.
